### ISSUE TITLE
Initial Features

### ISSUE THREAD

**Issue by TomCranitch** [UQComputingSociety/uqcsbot-discord#1]
I thought it would be useful to have a list of some of the features that I think that we need (and will aim to implement before release), as well as an incomplete list of other things we could add. If there is a list somewhere else already I'll get rid of this but I couldn't find it.

Must haves
- [x] Votey thumbs
- [x] Events
- [x] #jobs-bullitin messages
- [x] Welcome (I'm not sure if this is handled by something else in discord, I know a join log is common)
- [x] what are you working on messages 

Things I'm not sure if discord supports already
- [x] Google calendar integration (tbh it might be easier to migrate this to bot)
- [x] #15

Nice to haves
- [ ] Change bot status during events (not sure how this would work but maybe based on current live streams)
- [x] AOC
- [x] Dominos
- [x] Conduct
- [x] Emojify (might not have enough emojis for this RIP)
- [x] LaTeX
- [x] Repo
- [x] Uptime
- [x] XKCD
- [x] Yelling

**Comment by MaxwellBo** [comment]
I recall [pastexams](https://github.com/UQComputingSociety/uqcsbot/blob/master/uqcsbot/scripts/pastexams.py) and [whatsdue](https://github.com/UQComputingSociety/uqcsbot/blob/master/uqcsbot/scripts/whatsdue.py) getting used a lot in some of the subject channels. 

I'd nominate to implement them myself but I am contractually prohibited from doing so :(

**Comment by 49Indium** [comment]
Dominos is now complete (pastexams and whatsdue are also either complete or waiting to be merged). I'm unsure if we still need emojify, especially given the small number of emotes. I'm hoping to update the bot status in the next week or so, so we should be able to close this issue relatively soon.

**Comment by 49Indium** [comment]
We (2023 committee) are choosing to scrap the emojify command due to the lack of discord emote slots.

**Comment by andrewj-brown** [comment]
Alrighty bot gamers, it's a monumentous day. Following significant discussion* with the infra team, we feel it's time to finally close issue #1.

The only feature left on this list (as a tentative, this-might-be-cool) is some sort of gcal/events integration. This has its own issue (#59) and is 'hard' enough to warrant its own conversation happening there, rather than lumping it into this PR.

Congratulations and thanks to everyone who's contributed to the bot so far - while it's been just over 2 years, UQCSBot-Discord is now a sufficiently free-standing project (compared to the slack edition), and plays host to many of its own jokes and discord-isms. 

*Jimmy and I both reckon she'll be right.
