### ISSUE TITLE
Improvements to #yelling

### ISSUE THREAD

**Issue by JamesDearlove** [UQComputingSociety/uqcsbot-discord#57]
Some people are finding ways around our sacred #yelling channel rules, and should be fixed up. The two potential improvements are:
- [x] Detecting messages being edited, and alerting the channel
- [ ] Potentially blocking txt attachments
- [ ] Zalgo command
- [x] Consequences for repeated violations of the ALL CAPS policy

**Comment by ew-b** [comment]
Love it, let’s slap on a cool down mode as a consequence 🥰🥰

**Comment by bradleysigma** [comment]
I've been thinking about doing this, once the bot is updated to discord.py v2. Does the bot have mod permissions?

**Comment by JamesDearlove** [comment]
It should, and if it doesn't we can fix that

**Comment by peclarke** [comment]
one god, one bot. Give it ownership of the discord

**Comment by andrewj-brown** [comment]
the mod-like perms that uqcsbot currently has are:
- manage roles (only self-assignable + tutor role though)
- mention everyone, here, & all roles
- manage messages
- manage threads

It may need "manage channels" to enforce yelling via slowmode, but nothing else. I support the idea of keeping uqcsbot's privileges as minimal as possible and only adding when there's a clear use-case (e.g. mention everyone is something I don't think the bot should have, because there's no use-case, but I've been overruled on that).

**Comment by andrewj-brown** [comment]
new, semi-related improvement to add to this: /echo should convert messages to uppercase if they occur in #yelling

**Comment by 49Indium** [comment]
Bradley is working on this with #152 and #153
